### ISSUE TITLE
Ensure handle 'link' is absolute url

### ISSUE THREAD

**Issue by joshuashort** [code-423n4/code423n4.com#1041]
When displayed on the leaderboard, non-absolute urls (and non-urls) don't work as links.

* [x] fix impacted handles [#1042]
* [x] form validation
* [x] add placeholder text with absolute url
* [x] fix any new impacted handles (`handles/*.json` and `"link": "(?!http[s]?://|")`)

**Comment by hannahtuttle** [comment]
This brach is related to warden registration and needs to wait for warden auth to be merged before this is pushed into main just to make sure to avoid any merge conflicts.
