### ISSUE TITLE
Add date-based views to leaderboard (and all other future stats)

### ISSUE THREAD

**Issue by sockdrawermoney** [code-423n4/code423n4.com#1098]
Rather than having the only view be 'all time' stats for the leaderboard, let's:

- [x] use a rolling 90 days by default for all stats
- [x] create a toggle for the view which allows people to view stats over 3 months, 6 months, and “all time”

Dates should count back from the date of the last contest shown on the leaderboard.

**Comment by captainmangoC4** [comment]
Didn't see this issue before merging the leaderboard updates. The only thing that isn't done yet is making last 90 days the default. Keeping this open so we can do that.
