### ISSUE TITLE
Change defi protocol

### ISSUE THREAD

**Issue by sockdrawermoney** [code-423n4/code423n4.com#1108]
[Kuiper](https://kuiper.finance/) has launched and it's [pretty cool](https://thedefiant.io/kuiper-index-protocol-launches/). 

We can rename the `defiprotocol` contests etc to Kuiper

**Comment by itsmetechjay** [comment]
We have updated defiProtocol to reflect the Kuiper name on the contests pages and the text references on the Reports pages.
