### ISSUE TITLE
Leaderboard accounting error

### ISSUE THREAD

**Issue by sirhashalot** [code-423n4/code423n4.com#1117]
My total leaderboard amount did not change by the award amount mentioned in the Discord Announcement channel

1. Before Notional rewards were announced, I had $16,544.47 on the leaderboard: https://web.archive.org/web/20220205155638/https://code4rena.com/leaderboard
2. The Notional announcement in Discord should add $466.10 to this amount, which sums to $17010.57
3. The leaderboard instead showed $16,970.82, or roughly $40 less than expected. This amount no longer shows on the live leaderboard because of the new awards announced today, but the minor accounting error persists.

I report this in case it has impacted others, otherwise this can be closed because it is very minor.

**Comment by sockdrawermoney** [comment]
Please note the [comment from @CloudEllie in the #wardens channel](https://discord.com/channels/810916927919620096/810936719003090974/944341561695682613):

> 👋 Quick note re: the math in today's leaderboard update, which adds the findings from last month's Notional contest: some of you will notice minor differences between the awards you receive (per Jay's post in #announcements) vs the amounts added to your leaderboard totals. The reason for that is that Thunder judged the contest, but had also competed as a warden, so forfeited all winnings to remain impartial. As such, anyone who "shared" a finding with him got their winnings bumped up a bit -- but we want him to get full credit for his warden efforts on the leaderboard. 
> 
> Hope that makes sense 😂 -- hopefully will become clearer once the report is out!
