### ISSUE TITLE
[BUG]: User login using username and password not working

### ISSUE THREAD

**Issue by SaratAngajalaoffl** [code-423n4/code423n4.com#12868]
## Describe the bug
Unable to login using username and password

## To Reproduce
1. Go to Connect dropdown on the navbar
2. Click on Log In
3. Enter username and password
4. Shows error message

## Expected behavior
User should be logged in

## Screenshots
![image](https://github.com/code-423n4/code423n4.com/assets/60383339/6a2aaae0-f2a2-4fce-99c9-12aa6f27829d)

![image](https://github.com/code-423n4/code423n4.com/assets/60383339/8a637d1e-ff61-46f6-bbd6-99578400c973)

Login request is fulfilled successfully and returns a 200 response

## Desktop (please complete the following information):
 - OS: MacOS
 - Browser: chrome
 - Version: Version 116.0.5845.187 (Official Build) (arm64)

**Comment by SamusElderg** [comment]
@SaratAngajalaoffl can you please confirm you were able to login in the end? Or are you still having problems logging in?

**Comment by SaratAngajalaoffl** [comment]
Able to login now, thank you.

**Comment by SamusElderg** [comment]
Awesome, thanks for letting me know 🙏 I will close off this issue!
