### ISSUE TITLE
Add row number to leaderboard

### ISSUE THREAD

**Issue by 0xruhum** [code-423n4/code423n4.com#1297]
Currently, the leaderboard doesn't show the place of each competitor. Would be cool to have that, no?

```
1. cmichel
2. TEAM
      Watchpug
3. gpersoon
....
```

I tried to add it myself using CSS `counter-increment` but didn't manage to align the text properly :/

**Comment by sockdrawermoney** [comment]
@0xruhum this is a great idea!
