### ISSUE TITLE
Add Warden Certification Application page

### ISSUE THREAD

**Issue by tealtigrrr** [code-423n4/code423n4.com#1492]
**Description:**
We need to add a form for wardens to apply for certification from our site. The form will include a dropdown to select a warden Discord handle and an input for a GitHub username.

Data will be managed similarly to how we handle help tickets. Each form submission will generate a database item (ticket) where a warden's cert process can be tracked (though actual certification will be handled entirely by a third party).

@ninek9 @sockdrawermoney will provide copy.

**Resources:**
https://github.com/code-423n4/org/discussions/15

**Comment by joshuashort** [comment]
We'll need the Notion side set up -- and to have the `database_id` for the place that submissions go.

**Comment by tealtigrrr** [comment]
@joshuashort I can set that up. Does it just need to be a notion data base? Should I create a database item with some custom fields for discord handles and github user names?

**Comment by joshuashort** [comment]
> @joshuashort I can set that up. Does it just need to be a notion data base? Should I create a database item with some custom fields for discord handles and github user names?

Yep, I think so! Something more like wardenHandle and githubUsername -- unless we specifically want Discord name (not just the alias)

**Comment by joshuashort** [comment]
I'll need to field names eventually to map them, but that's what's being collected in the form.

**Comment by ninek9** [comment]
sock and i just realized we need an email address too

**Comment by ninek9** [comment]
Here's the copy for the "summary" of the agreement. I'll share the full agreement probably tomorrow which will also go on directly on the page as well. @sockdrawermoney 

---
### What's in this agreement?
- You accept the agreement by clicking “Submit” on this form,
- C4 intends to provide opportunities for folks that opt to become a Certified Contributor that include:
  - access to repos after contests conclude, post-contest triage, and mitigation review,
  - participation in private, invitation-only contests,
  - serving in multiple roles in a given contest,
  - providing individualized services to third parties as a subcontractor of C4 or C4’s Agent,
  - participating in C4 referral system to refer Participants to Sponsors for certain individualized services.
- Some contests may have limited number of opportunities for Certified Contributor participation,
- Certified Contributors will:
  - have their legal identity verified by a third party, who will be bound by a confidentiality agreement,
  - contribute in a timely and professional manner,
  - keep all confidential information secure and confidential,
  - abide by our Code of Professional Conduct[link],
  - not delegate their contributions to another party, and
  - not speak publicly on behalf of a sponsor, the C4 DAO or foundation, or C4’s agent.

**Comment by sockdrawermoney** [comment]
> you accept this agreement...

=> "provided your application is ultimately approved, you accept the agreement by clicking “Submit” on this form"

> as a subcontractor of C4 or C4’s Agent

I would drop 'as a subcontractor of C4 or C4’s Agent' and instead say 'arranged or facilitated by C4'

> "not speak publicly on behalf of a sponsor, the C4 DAO or foundation, or C4’s agent." 

=> "not speak publicly on behalf of a sponsor, the C4 DAO or foundation, or C4’s agent, outside of general advocacy of C4, and places where it is your role to do so"

> not delegate their contributions to another party

this one is a bit weird because 'delegate' and 'contributions' are both overloaded terms ('delegate' is a thing you can do with tokens, 'contributions' could sound like money). 

maybe instead:
> not have other people make C4 contributions that you imply were made by you

**Comment by sockdrawermoney** [comment]
also would change 'C4 intends to provide opportunities' to 'C4 may provide opportunities' because some of these are still in-progress concepts

**Comment by sockdrawermoney** [comment]
Form will also need to request an email address for them to be contacted at by our id verification provider @tealtigrrr @joshuashort

**Comment by ninek9** [comment]
full text of the agreement that needs to be included on the page, we should keep the formatting and paragraphs/numbering/indenting, etc. 

i don't think it needs to be included _before_ the submit button, but the above summary should, and this should be clearly available below the form.

let me know if that makes sense or if you have questions.

[Clean C4 Certified Contributor Terms D4 [21-008778-1870615843-353].docx](https://github.com/code-423n4/code423n4.com/files/8525621/Clean.C4.Certified.Contributor.Terms.D4.21-008778-1870615843-353.docx)
h

**Comment by ninek9** [comment]
from @sockdrawermoney:

> one additional request: we'll want to convert the doc to markdown for sure and make it easy for folks to track changes on that. it would be ideal if it was imported as a single markdown doc for the agreement so it's a nice and clean read on github with version history.

**Comment by joshuashort** [comment]
Hey @sockdrawermoney and @ninek9 -- here's an initial try at Markdown of the contributor terms; the numbering might be a little tricky (or need to be manual?) https://github.com/code-423n4/code423n4.com/pull/1493/commits/5ca1814aa93e44235359257df0b2bc24c4a444c7

**Comment by tealtigrrr** [comment]
@sockdrawermoney @ninek9 Showing change tracking in the doc is great, but if we have a significant change to the terms, would we alert the existing certified wardens of the change? Would we have a discord channel where we post updates?

**Comment by ninek9** [comment]
> @sockdrawermoney @ninek9 How are we going to be driving people to this form? Are we intending for it to be discoverable from the main site? Or will this live on a directly linked landing page that we will promote in places like twitter, discord channels, etc?

I believe we'll be making an announcement and direct linking, I don't think it should be discoverable. Will let @sockdrawermoney confirm though.

**Comment by ninek9** [comment]
> @sockdrawermoney @ninek9 Showing change tracking in the doc is great, but if we have a significant change to the terms, would we alert the existing certified wardens of the change? Would we have a discord channel where we post updates?

The second paragraph in the agreement addresses this. Essentially, we won't be obligated to, but in practice I would imagine a major change would have some public discussion around it.

**Comment by sockdrawermoney** [comment]
Yes, changes would be *at least* explained in Discord and likely discussed first.

Yes, we will be linking to this form specifically from the Discord and it won't need to be linked from other pages on the website.

**Comment by joshuashort** [comment]
@sockdrawermoney and @ninek9

Did a pretty naive conversion to Markdown -- replaced smart quotes with standards, tried to get the sections/lists expressed close to how they were.

But, it's not numbered the same way -- should I manually specify the numbers/letters for sections? If so, that's something that needs to be maintained with some care.

**Comment by sockdrawermoney** [comment]
No, markdown-based numbering and bullets are going to be fine.

**Comment by joshuashort** [comment]
(even with the section references to parts of the document?)

**Comment by tealtigrrr** [comment]
@sockdrawermoney @ninek9 I did a little bit of a re-write of the summary above, incorporating Sock's edits and adding some of my own (which I have `highlighted` using the code-highlighting feature): 

[Form asking for contact info] 

`About the Certified contributor role:
`
-  C4 intends to provide opportunities for approved Certified Contributors that include:
-  access to repos after contests conclude, post-contest triage, and mitigation review,
-  participation in private, invitation-only contests,
-  serving in multiple roles in a given contest,
-  providing individualized services to third parties arranged or facilitated by C4,
-  participating in C4 referral system to refer Participants to Sponsors for certain individualized services.
- `Note: ` Some contests may have limited number of opportunities for Certified Contributor participation _(moved this into this section as a "note" assuming it is meant to manage expectations that not all contests will provide these extra opportunities?)_


`Certified Contributors agree to:
`
-  have their legal identity verified by a third party, who will be bound by a confidentiality agreement,
-  contribute in a timely and professional manner,
-  keep all confidential information secure and confidential,
-  abide by our Code of Professional Conduct[link],
-  `not seek C4-related contributions from others and (explicitly or implicitly) take credit for them, and`
-  not speak publicly on behalf of a sponsor, the C4 DAO or foundation, or C4’s agent, outside of general advocacy of C4, and places where it is your role to do so


```
Please read the terms of the Certified Contributor agreement here:
[link to markdown]

By checking the box below and clicking “Submit” on this form—and provided your application is ultimately approved—you accept this agreement.

[ ] I have read and accept the Certified Contributor agreement (provided my application is approved)

[Submit button]
```

**Comment by tealtigrrr** [comment]
@sockdrawermoney @ninek9 @joshuashort I've made a list of what I believe are the final pieces to get this shipped. Anything missing?

- [ ] Form created & inputs integrated into Notion @joshuashort 
- [ ] Validation issues fixed @joshuashort 
- [ ] Wireframe updated with Summary text @tealtigrrr
- [ ] Final summary text approved @sockdrawermoney @ninek9
- [ ] Summary text, links and related form elements added to page @joshuashort 
- [ ] Final UI approved (including form labels, error and success messaging) @sockdrawermoney @ninek9

**Comment by tealtigrrr** [comment]
I've wireframed the Summary text and final form layout here: https://www.figma.com/proto/70Kn6T2bR8MDgeEHoI9hor/Contributor-Cert-Application-%5BWF%5D?node-id=2%3A2&scaling=min-zoom&page-id=0%3A1

(feel free to comment on the Wireframe or approve with a 👍  here)

**Comment by sockdrawermoney** [comment]
> (even with the section references to parts of the document?)

@joshuashort welp, lol maybe not. forgot there were references in the contract to other sections. your original thought is exactly what we'll need to do then:

> should I manually specify the numbers/letters for sections? If so, that's something that needs to be maintained with some care.

**Comment by ninek9** [comment]
> @sockdrawermoney @ninek9 I did a little bit of a re-write of the summary above, incorporating Sock's edits and adding some of my own (which I have `highlighted` using the code-highlighting feature):
> 
> [Form asking for contact info] 
> 
> `About the Certified contributor role: `
> 
> * C4 intends to provide opportunities for approved Certified Contributors that include:
> * access to repos after contests conclude, post-contest triage, and mitigation review,
> * participation in private, invitation-only contests,
> * serving in multiple roles in a given contest,
> * providing individualized services to third parties arranged or facilitated by C4,
> * participating in C4 referral system to refer Participants to Sponsors for certain individualized services.
> * `Note: ` Some contests may have limited number of opportunities for Certified Contributor participation _(moved this into this section as a "note" assuming it is meant to manage expectations that not all contests will provide these extra opportunities?)_
> 
> `Certified Contributors agree to: `
> 
> * have their legal identity verified by a third party, who will be bound by a confidentiality agreement,
> * contribute in a timely and professional manner,
> * keep all confidential information secure and confidential,
> * abide by our Code of Professional Conduct[link],
> * `not seek C4-related contributions from others and (explicitly or implicitly) take credit for them, and`
> * not speak publicly on behalf of a sponsor, the C4 DAO or foundation, or C4’s agent, outside of general advocacy of C4, and places where it is your role to do so
> 
> ```
> Please read the terms of the Certified Contributor agreement here:
> [link to markdown]
> 
> By checking the box below and clicking “Submit” on this form—and provided your application is ultimately approved—you accept this agreement.
> 
> [ ] I have read and accept the Certified Contributor agreement (provided my application is approved)
> 
> [Submit button]
> ```

Can the agreement markdown be imported directly into this page? I'd like to have the full agreement here without needing an extra click, if possible.  My thought was it could be below the Submit button, to keep the flow of the "application" reasonable. On that note we don't need the checkbox specifically, but if it provides a better UX that's fine too.

**Comment by joshuashort** [comment]
> Can the agreement markdown be imported directly into this page? I'd like to have the full agreement here without needing an extra click, if possible.

It's definitely possible. Updated with full body (no summary yet): https://deploy-preview-1493--code423n4-site.netlify.app/warden-certification-application/

**Comment by tealtigrrr** [comment]
I’m in the fence about putting _after_ the submit button because it seems a little, idk, tricky? “agree to this… but wait there’s more!”

I would feel more comfortable doing it if we have a check box that accepts the terms before the submit button.

Also we could save it as something to give them during the cert process.

**Comment by tealtigrrr** [comment]
> Can the agreement markdown be imported directly into this page? I'd like to have the full agreement here without needing an extra click, if possible. My thought was it could be below the Submit button, to keep the flow of the "application" reasonable. On that note we don't need the checkbox specifically, but if it provides a better UX that's fine too.

I think if we have the terms of the agreement after the submit button, having a check box acknowledging the terms _is_ actually better UX because it calls out that there are terms listed below. Like, I know checking those boxes is annoying, but ultimately, I think its a favor to the user, making sure they saw that there was more to the agreement they are essentially signing by hitting "submit."

**Comment by ninek9** [comment]
sounds good, thanks!
