### ISSUE TITLE
Maybe kinda not great formatting of code on reports

### ISSUE THREAD

**Issue by ninek9** [code-423n4/code423n4.com#154]
![Screen Shot 2021-07-23 at 2 26 01 PM](https://user-images.githubusercontent.com/602506/126843218-52d8b767-c2b5-4a3c-a423-e29f6d3c6a3a.png)

**Comment by ninek9** [comment]
On a Mac, browser is latest Microsoft Edge

**Comment by DianaPerkinsDesign** [comment]
![image](https://user-images.githubusercontent.com/3477197/130079576-e8fdea0e-2de7-455d-91d2-b2698624fde8.png)

Another example of a code block that needs a bit of styling attention
