### ISSUE TITLE
Sales pages

### ISSUE THREAD

**Issue by adamavenir** [code-423n4/code423n4.com#17]
I think we should write sales pages (so to speak) that lay out the value of participating for each of the audiences we're serving:

- sponsors
- pro solidity devs
- advanced white hats
- security researchers new to smart contracts 
- solidity devs new to security research

(the last two might be the same page)

**Comment by DianaPerkinsDesign** [comment]
Possible duplicate of #342 , please reopen if I'm mistaken :)
