### ISSUE TITLE
Add email confirmation to certified contribs application form (and update success msg)

### ISSUE THREAD

**Issue by CloudEllie** [code-423n4/code423n4.com#1841]
After someone submits the certified contributor application form, they should receive a confirmation message to clarify next steps. 

I'm thinking they should get both:

- an email confirmation, and
- a bit more info alongside the success message on the web form (which currently reads, "Thank you! Your application has been submitted.")

I definitely welcome suggestions as to how to make this clearer, friendlier, etc.!

## For the email

**Subject:** Certified warden application: what comes next

**Message:** 
Thank you for applying to be a certified Code4rena warden! Here's what to expect next: 

1. The DAO's AML/KYC agent, [Provenance](https://provenance.company/), will contact you to certify your identity. **Please watch for an email that will come directly from Provenance (https://provenance.company/).** 
2. Provenance will lead you through your identity verification process, and ask you to sign an agreement binding you to a code of conduct and non-disclosure. Code4 Corporation and the Code4rena DAO do NOT have access to your personal information, simply the verified knowledge that you have (or have not) been certified.
3. Code4 Corporation will contact you to let you know when your application has been approved.

This process is entirely managed by humans, so it can take a while to complete. We appreciate your patience with the process!

The Code4 team

## For the success message

Thank you! Your application has been submitted, and we will review it ASAP. Please note:

- You should receive a confirmation email shortly;
- If you meet the [eligibility requirements](https://docs.code4rena.com/roles/wardens/certified-wardens#who-is-eligible-to-be-a-certified-contributor), you will be contacted by the DAO's AML/KYC agent, [Provenance](https://provenance.company/), to certify your identity. **Please watch for an email that will come directly from Provenance (https://provenance.company/).** 
- Every application is processed individually, requires several people's input, and takes time to review. We appreciate your patience!

More details on this process can be found in the [C4 docs](https://docs.code4rena.com/roles/wardens/certified-wardens#who-is-eligible-to-be-a-certified-contributor).

**Comment by captainmangoC4** [comment]
I'll include the same caveat ("If you meet the eligibility requirements"), in the first bullet of the email confirmation too.
