### ISSUE TITLE
Contest reports should be sorted by release date rather than contest date

### ISSUE THREAD

**Issue by IllIllI000** [code-423n4/code423n4.com#1848]
It's hard to keep track of which new reports are release by solely using the contest web page because they are shown by contests date rather than report release date. When one opens a report, the date listed is the report date, so the information is available, and should be used for sorting.

**Comment by CloudEllie** [comment]
True, though I think the contest run dates are also important, especially for returning sponsors where readers will want to differentiate between multiple contests sponsored by the same team/project. So the ideal might be to have multiple sorting options.

**Comment by captainmangoC4** [comment]
We actually don't store publish date, so this would require adding that info to report data.

**Comment by IllIllI000** [comment]
> We actually don't store publish date, so this would require adding that info to report data.

If you do update it, it would be good to include the contest's judge as well

**Comment by sseefried** [comment]
It shouldn't be too hard to do some archaelogy and discover the publish dates and the judges. I'd be happy to help.

**Comment by scaraven** [comment]
I think an update such as this will definitely help wardens learn. It should be straightforward to scrape the judge names from the reports and the date of publishing through the merge requests on github

**Comment by IllIllI000** [comment]
If someone provides a PR containing the new columns appended to contests.csv, would that be able to be merged immediately, or is there other internal tooling that also needs to change before that can be done?
