### ISSUE TITLE
Contest leaderboard should be accessible via report page.

### ISSUE THREAD

**Issue by Ellahinator** [code-423n4/code423n4.com#1855]
Currently, if you go on a contest report page, the only way to see the leaderboard of that specific contest is to go to the contest page, scroll and find that contest and click view contest. 
The contest leaderboard should be easily accessible via the report page imo.

**Comment by sockdrawermoney** [comment]
Personally I see these as different audiences. Reports are a formal document for the purposes of sponsors. They do list contributors in the order of their rankings, but it seems a better fit to keep the contest related aspect scoped to the contest page and let the reports be presented more as "sponsor business"

**Comment by sockdrawermoney** [comment]
Oh wait -- maybe I misunderstood. If your point is that the contest page should be linked from the report page, I completely agree with this. I thought someone had raised this and implemented it a couple months ago but it doesn't look like that happened.

**Comment by IllIllI000** [comment]
I did: https://github.com/code-423n4/code423n4.com/issues/1702

**Comment by IllIllI000** [comment]
Hmm, looks like the report page now contains the link to the contest under the 'Scope' heading. I'll close mine

**Comment by Ellahinator** [comment]
> E.g. https://code4rena.com/reports/2021-12-vader/ does not link to https://code4rena.com/contests/2021-12-vader-protocol-contest

> Hmm, looks like the report page now contains the link to the contest under the 'Scope' heading. I'll close mine

The link under scope is the [github repo](https://github.com/code-423n4/2021-12-vader), not the [contest page](https://code4rena.com/contests/2021-12-vader-protocol-contest). @IllIllI000

**Comment by joshuashort** [comment]
> > E.g. https://code4rena.com/reports/2021-12-vader/ does not link to https://code4rena.com/contests/2021-12-vader-protocol-contest
> 
> > Hmm, looks like the report page now contains the link to the contest under the 'Scope' heading. I'll close mine
> 
> On https://code4rena.com/reports/2021-12-vader/, the link under scope is the [github repo](https://github.com/code-423n4/2021-12-vader), not the [contest page](https://code4rena.com/contests/2021-12-vader-protocol-contest). @IllIllI000

There are a few things going on here -- site navigation and the contents of reports. In a way this relates to #1085; it's nice to have a route directly to a report, but maybe it also makes sense to have a report tab (like the results tab) on a contest page (e.g. https://code4rena.com/contests/2022-04-axelar-network-contest).

Then the contest leaderboard would be accessible via the report page -- because they'd just be different tabs on the same page (when viewing from the 'contest' page).

Also, the current report 'pages' could have navigation items added in the layout, leaving report contents as a separate thing.

**Comment by IllIllI000** [comment]
My bad - you're right, I got confused. I'll reopen it if the fix for this one doesn't happen address it too

**Comment by SamusElderg** [comment]
This is now covered by the new app that landed towards the end of last year, closing this issue for now 🙏
