### ISSUE TITLE
Inputs work

### ISSUE THREAD

**Issue by Simon-Busch** [code-423n4/code423n4.com#1864]
Re-think the inputs and validation 
- create proper reusable validation
- create generic global inputs rather than formfield > widgets

**Comment by captainmangoC4** [comment]
I started working on this as part of the warden auth feature. #2030

**Comment by Simon-Busch** [comment]
@captainmangoC4  Is it already done yet ? Otherwise maybe it would be great to make it in a separate PR to try to reduce the weight of the PR ?! :-)

**Comment by SamusElderg** [comment]
This is mostly covered by the app now, but also there is a main issue up in regard to an 'input' component that would cover the concerns raised with this issue 👍
