### ISSUE TITLE
Upcoming contests is still shown even when there are not upcoming contests

### ISSUE THREAD

**Issue by dabushori** [code-423n4/code423n4.com#1879]
The "Upcoming Contests" title is still shown in the [main](https://code4rena.com) page even when there are no upcoming contests.
![image](https://user-images.githubusercontent.com/37002682/169245333-7620bc7f-f86e-4da9-987d-a818cdd9423b.jpeg)

**Comment by dabushori** [comment]
Also the active contests title is not shown

**Comment by Simon-Busch** [comment]
This will be fixed in a new feature we are working :-)
