### ISSUE TITLE
Leaderboard filtering improvement

### ISSUE THREAD

**Issue by Simon-Busch** [code-423n4/code423n4.com#1935]
Improve filtering capacity for the leaderboard : 
- Filter by contests
- Filter by type of findings 
- Combine filtering

That would be a first step to improve our analytic before heavy duty analytic work on the leaderboard

**Comment by tealtigrrr** [comment]
@sockdrawermoney tagging you for potential discussion on this 🙂

I think this might dovetail nicely with other plans to contextualize our past contest data on the leaderboard.

**Comment by sockdrawermoney** [comment]
I’d start with a toggle that shows # per contest and aggregate total. 

I think there’s some more discussion to be had on implementation beyond that, some of which aligns with a mason initiative we are going to share soon.

**Comment by joshuashort** [comment]
There's now a simple leaderboard endpoint that can filter by ranges (hard coded 2022, 2021, Prev60, Prev90) and contestId: https://github.com/code-423n4/code423n4.com/pull/5899

Now, it's pretty trivial to implement filtering by:
* a more extensible range (YearXXXX and PrevXXX at least)
* finding risk
* finding split

**Comment by SamusElderg** [comment]
Adding this as a ref to another similar issue in the main repo but its mostly covered by the app and ongoing plans 🙏
