### ISSUE TITLE
Markdown math support 

### ISSUE THREAD

**Issue by joshuashort** [code-423n4/code423n4.com#1961]
GitHub has added support for TeX/MathJax (https://github.blog/2022-05-19-math-support-in-markdown/); can we add support for:
* [x] the report pages (similar to #1683)
* [x] the preview tab of the findings form

**Comment by Simon-Busch** [comment]
it seems that with the plugin we are using now we will be limited. I saw your other related issue ( https://github.com/code-423n4/buttons/issues/148 ).

Will make some research
