### ISSUE TITLE
Text area size limit cause error on help page

### ISSUE THREAD

**Issue by IllIllI000** [code-423n4/code423n4.com#1962]
I submitted a help request today and got: `body.children[0].paragraph.rich_text[0].text.content.length should be ≤ 2000, instead was 4813` when the error page loaded. The maximum sizes of both this and the report submission fields are both known ahead of time, so the html forms should be able to use javascript to reject the request before the form is actually submitted. This may seem like an insignificant difference, but with the current method, when we get the error page, if we hit the browser back button, all of the previous fields are cleared and we have to enter everything all over again, which is very tedious.

**Comment by IllIllI000** [comment]
The maximum help form size should also be increased - see https://discord.com/channels/810916927919620096/824698635815223316/978956827821748225

**Comment by Simon-Busch** [comment]
Hey @IllIllI000 ,

Can you tell when on which page it happened ? Help page or Submit findings page ?

Just to make it clear, that happens because the content of the textarea was too large ?
