### ISSUE TITLE
[UX] Design Modal UI

### ISSUE THREAD

**Issue by tealtigrrr** [code-423n4/code423n4.com#1974]
Design generic Modal:

Title
Body
Action and cancel buttons
Close icon

**Comment by tealtigrrr** [comment]
Here is the mockup for this @Simon-Busch 
https://www.figma.com/file/k6Ns4W5m4ruRj5ECfiyAnD/Generic-Modal-Design?node-id=2%3A2

**Comment by tealtigrrr** [comment]
I also created a new icon for closing the modal, because I didn't see one in our .com library
![close-icon](https://user-images.githubusercontent.com/92493154/170500257-986c8b10-d94a-4f4a-a35b-c0046e96bb64.svg)
.

**Comment by tealtigrrr** [comment]
lol I guess if you upload a tiny square svg to github, it displays it at full width which makes it huge 😆

**Comment by Simon-Busch** [comment]
Done :) https://github.com/code-423n4/code423n4.com/pull/2012/
