### ISSUE TITLE
A "random" image is taken as the default avatar for those not having submitted one

### ISSUE THREAD

**Issue by axic** [code-423n4/code423n4.com#1994]
<img width="391" alt="Screenshot" src="https://user-images.githubusercontent.com/20340/170245421-0e7691ce-b54d-4508-971b-bc1fc81faea1.png">

**Comment by joshuashort** [comment]
Yep. Nothing is assigned to someone that didn't provide an avatar; I'd agree it's a bit weird that they all get the same placeholder, if that's what's meant. This'll likely be solved by switching to a different type of placeholder; for those that want an avatar, they can give one.

**Comment by SamusElderg** [comment]
Closing this issue as completed/solved now, thankyou! 🙏
