### ISSUE TITLE
Proposed website enhancements

### ISSUE THREAD

**Issue by adamavenir** [code-423n4/code423n4.com#2]
Near-term:  
- [x] Add readme content to website
- [x] Add judging criteria to website
- [x] Add submission policy to website
- [x] Add current contest info to home page

Next:  
- [ ] Create page for each sponsors’ contest
- [ ] List avatars / social links / (bios?) of wardens and judges
- [ ] Create ‘register’ page for participants to submit their info for inclusion

Later:  
- [ ] ~~Build site on gatsby (or similar) to allow easy content edits~~

Thoughts?

**Comment by zscole** [comment]
Yeah, this seems like a good roadmap, although I would argue against using Gatsby in the long-term (or at all ;)) in favor of React. 

Eventually, if this takes off, we'll likely have some a dapp with associated governance functionality, so it would be better to plan for that instead, IMO.

**Comment by adamavenir** [comment]
@zscole That sounds just great to me :) I was mostly trying to tease out where folks see it going!

**Comment by adamavenir** [comment]
I’ve been putting thought the last couple days into how we should architect the site.

To build on what’s described above, these are the features that I think we need.

## Features

- Store and edit contest, sponsorship, reporting guidelines, and most “internal” site pages in markdown files.
- Add a contest announcement, details, links, timeline, and registration
- Display active contests with start/end countdowns
- List completed contests
	- participants/teams and awards
	- what else?
- Leaderboard with historical listing of all participants and awards
- Form for sponsor inquiries
- Form for warden registration

## Choice of platform

I can handle plain vanilla React just fine, but I’d prefer to build with a framework, as I don’t see our needs (at this point) as overwhelmingly needing custom and the needs I’m seeing right now seem like they’d be a great fit for a static site framework like Gatsby or Next.js. 

Regardless of which framework we use, I think there is real benefit to using Netlify for the site.

### Why Netlify

There are some extremely handy built-in capabilities with Netlify that have led me to choose it as an absolute go-to for the past couple years.

1. Netlfy forms — quickly stand up and edit forms to route data via webhooks (to, say, discord) without having to build any handlers.
2. Netlify CMS — barebones CMS that allows for editing of content. It’s nice to be able to add and modify site data without having to directly edit JSON blobs. This is an awesome option for that.
3. GitHub integration. Basically once it’s configured, you never really have to think about Netlify again, as all pull requests get auto-built previews on every push, and Netlify will auto-deploy to production on merges to main.

I’ve built a number of sites using Netlify CMS, which is a novel approach for managing static site data. Markdown and JSON files (etc) can be edited in a UI and those edits can show as pull requests in GitHub or as ‘drafts’ in Netlify CMS, so they can be reviewed and integrated accordingly. 

Take tricitiesvote.com as an example of one site I built, which pulls in data from public APIs for candidate pamphlet data and donor records, stores them in JSON, and then that data can be edited in a GUI by folks without having to understand how the site data is structured, while also allowing folks to review and make changes on GitHub.

My experience is in building Netlify CMS on top of Gatsby, but I know it’s possible to do with Next.js and not terribly different.

# Framework options

### Option 1: Gatsby
I’ve built a lot with Gatsby, and I can stand things up relatively quickly with it. I don’t see any problem building out all of the above. This would be the easiest, fastest result given how much I’ve done in the past on the platform.

## Option 2: Next.js
I’ve not built anything with next.js yet, but I don’t anticipate any challenges as the docs are stellar, and the team behind it is awesome. This would be a bit slower due to learning curve on a new platform, but I would be happy to build on Next as I’ve been looking for a project to try it out with.

## Option 3: vanilla react
I’d be fine going this route, though it would be slower for me to ship than the previous two because I’d have to handle more bespoke stuff. I’m not opposed to this in the slightest, as there may be future functionality envisioned that would require a rebuild of whatever was executed on Gatsby or Next.js. Thus, if the vanilla react option is most desirable, what would be useful to me is to get a sense for what features we’d be potentially wanting to build so that I can consider the data model in that context, and it would also be interesting to know whether those potential future features might be best served on a separate domain.

Absolutely open to other suggestions, too. :)

**Comment by zscole** [comment]
Gatsby is the lowest-hanging fruit here and Netflify is pretty simple to use. For the short term, I would say let's go with Option 1.
