### ISSUE TITLE
Include High & Medium Risk Finding belongings in Discord's announcement channel

### ISSUE THREAD

**Issue by 0xSorryNotSorry** [code-423n4/code423n4.com#2138]
When the awards are announced in the Discord's announcements channel, include how many high/medium risks are found by the particular warden / team.

It's like:

```
Awards for AbraNFT:

8053.09 MIM » gzeon **(2 HR - 4 MR)**
7546.85 MIM » hyh **(2 HR - 3 MR)**
5930.51 MIM » BowTiedWardens (BowTiedHeron, BowTiedPickle, m4rio.eth, Ðravee, BowTiedFirefox) **(1 HR - 3 MR)** 
```

**Comment by Simon-Busch** [comment]
I worked on this here : https://github.com/code-423n4/buttons/issues/165 
So I will close the issue here :-)
