### ISSUE TITLE
Change contests to end on the hour bondary

### ISSUE THREAD

**Issue by IllIllI000** [code-423n4/code423n4.com#2182]
Can the contests end at the start of the new hour (i.e. HH:00:00.000), rather than the minute before the end (i.e. HH-1:59:00.00)? If need be, new contests can start at a minute past the hour

**Comment by sockdrawermoney** [comment]
Lol good point. 

I think this is just an anachronism left over from swapping over at 0 UTC, but we've moved that time for US work hour purposes. 

No reason we can't change the start/end hours as you suggest.

**Comment by itsmetechjay** [comment]
We are implementing this change.  Contests starting after 6/22/22 will start and end at 20:00 UTC.
