### ISSUE TITLE
Arbitrary file can be read

### ISSUE THREAD

**Issue by csanuragjain** [code-423n4/code423n4.com#2187]
In get-user.ts, the passed user handle id is not sanitized. Attacker can simply use below URL to access internal directories

${event.headers.origin}/.netlify/functions/get-user?id=${handle} where malicious id can be like ../../some_other_file.json

## Problem:

const userFile = readFileSync(`./_data/handles/${userHandle}.json`); is directly trusting the value of userHandle where const userHandle = event.queryStringParameters.id; Since this value is not sanitized so attacker can easily give malicious path

## Recommendation
Use the isDangerousHandle(id) function to get rid of malicious input which is used currently in other functions

**Comment by csanuragjain** [comment]
Just to add, the url need to be accessed using Proxy Interceptor like Burp Suite which will not process .. before sending it to server. As a shortcut even Mozilla Firefox edit and resend feature can be used in network console to send this request

**Comment by eugenioclrc** [comment]
Ok so what if we put the functions `isDangerousHandle` and `isDangerousRepo` in a helper utilities file like `_utils.js` so we could share the function logic.
Then we could import it on [`users.ts`](https://github.com/eugenioclrc/code423n4.com/blob/14c4ba945235ffd81359c534220e2d6464f4165d/functions/users.ts#L2)

**Comment by csanuragjain** [comment]
yes I think that is a good idea

**Comment by Simon-Busch** [comment]
@captainmangoC4, is this issue still on ?  Or has it been done in another branch ? :-) 

I saw that the PR(https://github.com/code-423n4/code423n4.com/pull/2195)  from @eugenioclrc  was closed ?

**Comment by captainmangoC4** [comment]
@Simon-Busch thanks for asking! I forgot what this issue was originally about. Yeah, it is still open. We need to add the same “isDangerous” check in get-user and get-teams.
