### ISSUE TITLE
No max limit on email address - Spamming

### ISSUE THREAD

**Issue by csanuragjain** [code-423n4/code423n4.com#2189]
## Filename:
submit-finding.js

## Issue
While submitting issues in team, warden can specify 100's of email address in emailAddresses. This can be used to spam any user

## Recommendation
Apply max number of emails by checking emailAddresses.length

**Comment by csanuragjain** [comment]
Also it would be great to have IP based rate limit which could allow further restriction.

**Comment by eugenioclrc** [comment]
What if we also add some mail validation/sanitization, somthing like;
```js
  // filter & sanitize mails
  email = (email || '').toLowerCase().split(',').map(e => e.trim()).filter(e => /\S+@\S+\.\S+/.test(e));
  // remove duplicates
  email = [...new Set(email)].slice(0, MAX_LIMIT).join(', ')
```

**Comment by csanuragjain** [comment]
slice(0, MAX_LIMIT)  this might cause confusion, since user wont know why other remaining emails were not processed.

**Comment by eugenioclrc** [comment]
True, i have add a pull request with a validation of the amount of mail address, and also a simple regex validation of each mail address.
