### ISSUE TITLE
Add reports and posts for past contests

### ISSUE THREAD

**Issue by adamavenir** [code-423n4/code423n4.com#22]
ElasticDAO report: http://bafybeicvxkopnuuxzitpf6vfh5gvglfooxr5fos36327gilky5nvqz757y.ipfs.localhost:8080/?filename=Code%20423n4%20ElasticDAO%20Findings%20and%20Analysis.pdf

ElasticDAO medium post: https://medium.com/code-423n4/40k-awarded-30-smart-contract-bugs-found-in-helping-elasticdao-launch-more-securely-c30df67593dd

**Comment by DianaPerkinsDesign** [comment]
@adamavenir Is this still needed?

**Comment by adamavenir** [comment]
Lol nah this is pretttty stale :)
