### ISSUE TITLE
Account management page

### ISSUE THREAD

**Issue by captainmangoC4** [code-423n4/code423n4.com#2257]
Allow users to edit:
- username
- linked discord username
- linked github username
- social link
- avatar
- addresses
- default address

Allow users to see:
- all of the above plus
- teams they are on
- link to create a new team

Nice to have:
- if wardens meet corresponding criteria:
  - link to judge application
  - link to "certified +" application

**Comment by Simon-Busch** [comment]
Great idea ✌🏼

Wouldn't it be part of the warden profile ? Which could include a EDIT button  ?
