### ISSUE TITLE
Add soft-failed msg signing handling to warden registration

### ISSUE THREAD

**Issue by SamusElderg** [code-423n4/code423n4.com#2267]
**Issue:**
In instances:
1. After completing the warden registration form, the user can select 'Register with MetaMask' or 'Register with WalletConnect' (maybe the same with registering a team)
![image](https://user-images.githubusercontent.com/26967164/174483829-2c4608d1-13e9-4ed6-9a8c-27a319f1314e.png)
2. When choosing a wallet to connect to
![image](https://user-images.githubusercontent.com/26967164/174485195-672360d7-693f-4c15-a8da-55c6acbc6c45.png)
3. *Check all instances where a message needs signing and update issue if relevant/additional*

If the user selects one of these and then soft-fails the message signing for one reason or another (maybe their hardware wallet is locked, maybe the RPC is down/wrong/having issues, user's wallet might have a broken queue with a previous stuck txn in the way... there are many legit reasons), we do not catch this error. We do however check to see if the user cancels the message signing which is excellent (via `if (user === undefined)` after the async 👍

This leaves the user unable to go back or forward or try again:

![image](https://user-images.githubusercontent.com/26967164/174483723-b0400e8b-ce36-4f34-92d1-c416d860117a.png)

The only option from there is to refresh the page and enter the form again. In the case of a hardware wallet locking after X seconds, it's highly likely the same thing will happen to the user again the 2nd time around if they are entering a good amount of information for the 'Qualifications' form field 😂

In the case of connecting a wallet, the toast is actually covering up access to the 'connect wallet' button so same deal: you have to refresh the page to try again

![image](https://user-images.githubusercontent.com/26967164/174486199-727fdb91-a4d4-4675-9786-0322fe48c7e0.png)

**Solutions:**
Option 1 - Bare Bones / Reliable
- a: We can simply provide a cancel/back button to cancel the current 'txn in process' state and allow the user to try again from the 'Register with MetaMask' or 'Register with WalletConnect' stage with the form in tact
- b: In the case of wallet connection flow, maybe just add a 'close' (or better UX is probably 'cancel') button to the "Logging in..." toasts so the user can cancel and clear the toast, clear the current onchain call to get it out of the way and try again with a toast dismissal: `const dismiss = () =>  toast.dismiss(toastId);`

Option 2 - Automated / Assuming ( i suspect this wont work, based on the moralis library)
- We should be able to catch these specific errors, but not sure why `if (user === undefined)` is not triggering though, leads me to suspect its stuck in the `await` phase still despite technically failing (in `web3-react` this is a caught error for sure, i don't have a lot of experience with the moralis library though). 
- Either way might need to experiment with changing:
`          const user = await authenticate({
            provider,
            signingMessage: "Code4rena registration",
          });`
to something like:
`          const user = await authenticate({
            throwOnError: true,
            onError: (error) => {updateErrorMessage("Problem signing message")},
            provider,
            signingMessage: "Code4rena registration",
          });`
- Or do the await `.then(user)` -> `.catch(error)` method
- If that doesn't work the moralis library might not actually have the ability to catch this which would be a bit disappointing (in that case id fall back to checking the states in `MoralisContextValue.auth` to see if there is a way to custom-detect without getting hands too dirty)

Option 3 - The irky option
- Add a timer to the authentication await, that simulates the behaviour of option 1b on a timer. I think this is a bad UX option personally but if hashed out with more thought and a clever twist, may be a viable option

**Comment by captainmangoC4** [comment]
Thanks for your thoughts on this, Samus! I hadn't even thought of this failure case. I'll look into the options you suggested.

**Comment by SamusElderg** [comment]
Ill close this off now, i believe this is fixed! thanks!
