### ISSUE TITLE
Refactoring: Use single form component

### ISSUE THREAD

**Issue by Simon-Busch** [code-423n4/code423n4.com#2306]
## Problem/opportunity:
* As we expand our main repo, we need to keep our component concise and avoid duplicates

## Desired outcome
* Refactor code to improve maintainability 

## Proposed solution:
* Convert our form component to TS component 
* Use it in Register Form, Team registration Form, submit Findings, Help

**Comment by SamusElderg** [comment]
Closing this one off, this is pretty well covered now (and anything that isnt has an existing issue, ie. the input/form component feat/issues)
