### ISSUE TITLE
[FEATURE]: Self-serve issue editing

### ISSUE THREAD

**Issue by sockdrawermoney** [code-423n4/code423n4.com#2762]
## Problem / opportunity:
- CAs spend a lot of time updating submissions on behalf of wardens. 

## Desired outcome
- Wardens can see their submissions and make self-serve edits to them.

## Solution
- at the top of the submission form, add a link to a page (`https://code4rena.com/contests/YYYY-MM-contest/{warden_handle}`) with a list of submitted issues for the selected contest (available via GitHub API)
- allow them to click any of any of them to view `https://code4rena.com/contests/YYYY-MM-contest/{warden_handle}/{github_issue_number}`
- click to edit any of them, go to `https://code4rena.com/contests/YYYY-MM-contest/submit/{github_issue_number}`
- pre-populate the submission form 
- upon submit, replace the original issue content via the API and send an email confirmation.

If part of a team, wardens should be able to see all of that team's submissions.

Bonus: this essentially allows wardens to draft their submissions during the contest, and would allow teams to view/edit/update team members' findings.

**Comment by joshuashort** [comment]
Will also have to keep an eye on #1109
