### ISSUE TITLE
[BUG]: after submitting a finding and clicking "submit another one" the "Links to affected code" is not cleared

### ISSUE THREAD

**Issue by StErMi** [code-423n4/code423n4.com#2774]
## Describe the bug
When I submit another issue the "Links to affected code" is not cleared and it always show the last one I have added

## To Reproduce
1. Submit a finding that requires you to fill "Links to affected code"
2. Submit the finding
3. Click to submit another one
4. The first row of "Links to affected code" is not cleaned

## Expected behavior
When I click to submit another finding the whole form should be in a clean state

## Desktop:
 - OS: MacOS
 - Browser: chrome
 - Version: 103

**Comment by pashov** [comment]
Noticed the same thing yesterday.

**Comment by captainmangoC4** [comment]
I believe this was fixed by #2814
