### ISSUE TITLE
Disallow space character in warden handles

### ISSUE THREAD

**Issue by CloudEllie** [code-423n4/code423n4.com#2870]
## Description
Currently, the warden registration form allows space characters, but Github doesn't allow spaces in usernames. 

For example, applicant submits `Two Words`; on our end (Github PR) we see `Two-Words` and their Discord name is `Two Words`. 

Ideally would be nice to just nip that in the bud and disallow usernames with spaces to be submitted through the registration form.

**Comment by SamusElderg** [comment]
@CloudEllie is this still relevant? If so want me to handle it?

**Comment by CloudEllie** [comment]
Hmm, let's ask @captainmangoC4 😄

**Comment by SamusElderg** [comment]
This is sorted now for C4 usernames 👍 will close this off as completed!
