### ISSUE TITLE
[BUG]: Metamask detection isn't working consistently; connect wallet UX

### ISSUE THREAD

**Issue by sockdrawermoney** [code-423n4/code423n4.com#2950]
## Describe the bug
I have metamask installed but am still prompted to install it.

I have other wallet UX feedback as well.

<img width="298" alt="Screen Shot 2022-07-16 at 10 26 45 AM" src="https://user-images.githubusercontent.com/110551/179347159-365df4e3-e459-440b-9a6c-d2f362c288ac.png">

I understand the intent to flag the correct action, but this is just a bit clunky in this menu. 

Let's simplify a bit:
-  I would just have it say 'Metamask' and 'WalletConnect' as the wrapping dropdown prompt already says 'Connect wallet', so anything else is redundant. 
- Clearly the 'install' case isn't triggering as universally as we'd like, but regardless, from a UX perspective, I'd rather just display a prompt when they click 'metamask' and we get an error because they don't have it installed; the 'install metamask' feels a little too hand-holdy for the general sophistication of our audience.

<img width="1052" alt="Screen Shot 2022-07-16 at 10 30 11 AM" src="https://user-images.githubusercontent.com/110551/179347234-726aa1c4-efc3-4bd0-b2ca-eac89be2ce19.png">

- "login" is a noun; "log in" is a verb. We want "Log in" here. 
- Would also suggest just using a heading above the two buttons that says "Connect wallet" with just "MetaMask" and "WalletConnect" below.

**Comment by tealtigrrr** [comment]
@sockdrawermoney I added this to our Dev Requests project board to keep track of it. I assigned it a "medium" priority and designated it as a cool-down type activity. Let me know if that's out of line with what you're thinking for this.

**Comment by captainmangoC4** [comment]
I've started addressing these while I'm working on alt sign-in options

**Comment by captainmangoC4** [comment]
It's so weird that this isn't working. This is how they say to detect MetaMask in their docs: https://docs.metamask.io/guide/getting-started.html#basic-considerations

I'm not sure how else to detect it, but I went ahead and implemented your suggestion to call it out in the error message instead of in the button. All of these suggestions are addressed in https://github.com/code-423n4/code423n4.com/pull/4179
