### ISSUE TITLE
Findings submission form submits contest name as contest ID

### ISSUE THREAD

**Issue by dstaley** [code-423n4/code423n4.com#320]
The findings submission form submits the actual contest title as the ID field instead of the numeric value, which creates a bit of a headache when processing judging sheets.

**Comment by DianaPerkinsDesign** [comment]
We should check if this is still true

**Comment by joshuashort** [comment]
It does still seem to be the case.. checked the `data/*.json` files in a findings repo -- the `contest` field is a title.

**Comment by joshuashort** [comment]
There are a couple of changes to identify for this.. starting a branch for the buttons-side changes.
