### ISSUE TITLE
Update Homepage Hero

### ISSUE THREAD

**Issue by tealtigrrr** [code-423n4/code423n4.com#341]
**Description:**
Update text on homepage hero section and add two CTA buttons.

**Content:**
Text:
- Possible headline: _“The Future of Audits is decentralized”_
- Remove the role definitions (we'll re-add them somewhere else!)

CTAs - _both link to pages of the same title_
- [Get an Audit >](https://github.com/code-423n4/code423n4.com/issues/342)
- [Compete in a contest >](https://github.com/code-423n4/code423n4.com/issues/343)

**Design:**

**Comment by DianaPerkinsDesign** [comment]
This is live! 🍕
