### ISSUE TITLE
Create "Get an Audit" page

### ISSUE THREAD

**Issue by tealtigrrr** [code-423n4/code423n4.com#342]
**Description:**
Create page that explains how the C4 audit process works and provide potential sponsors with next steps.

**Content Needed:**
- Contest role definitions (from previous homepage hero)
- How a contest works
- ??

**Design Mockup:**

**Comment by tealtigrrr** [comment]
@sockdrawermoney Are this & issue #343 still something that we want to add to the site in the near term? I'm guessing you'll have a lot of marketing ideas coming back fresh from Devconnect, so I wanted to surface this and see what approach we want to take, strategy-wise. Thanks!

**Comment by SamusElderg** [comment]
Closing this one off as i believe its covered by the current website content 🙏
