### ISSUE TITLE
[BUG]: Judge application submit form fails when not logged in

### ISSUE THREAD

**Issue by JeeberC4** [code-423n4/code423n4.com#3568]
## Describe the bug
When a warden is not logged in, if they submit a Judge Application there is no warning or pop-up, the page just sits.

## To Reproduce
1. Go to 'https://code4rena.com/judge-application/'
2. Enter information
3. Scroll down to 'Apply to be a Judge'
4. See nothing happen

## Expected behavior
A warning or reminder should show reminding the user to log in in order to submit the form.

## Screenshots
N/A

## Desktop (please complete the following information):
 All versions, all browsers

## Smartphone (please complete the following information):
 N/A

**Comment by tealtigrrr** [comment]
Wrap this page in a protected page component.

**Comment by joshuashort** [comment]
Some semi-related cleanup to pull in: https://github.com/code-423n4/code423n4.com/tree/dzhawsh/judge-form-cleanup
