### ISSUE TITLE
[BUG]: Clickjacking risk

### ISSUE THREAD

**Issue by CloudEllie** [code-423n4/code423n4.com#3843]
## Describe the bug
The following issue was submitted by a new warden, via the Help Desk. I'm pasting the contents of the help desk submission here. 

…

While performing security testing https://code4rena.com/I have found the vulnerability called Clickjacking.

What is Clickjacking ?
Clickjacking (User Interface redress attack, UI redress attack, UI redressing) is a malicious technique of tricking a Web user into clicking on something different from what the user perceives they are clicking on, thus potentially revealing confidential information or taking control of their computer while clicking on seemingly innocuous web pages.
The server didn't return an X-Frame-Options header which means that this website could be at risk of a clickjacking attack. The X-Frame-Options HTTP response header can be used to indicate whether or not a browser should be allowed to render a page in a <frame> or <iframe>. Sites can use this to avoid clickjacking attacks, by ensuring that their content is not embedded into other sites.
This vulnerability affects Web Server.

Steps to Reproduce:
Put https://code4rena.com/ url in the code of iframe, which is given below

<!DOCTYPE HTML>
<html lang="en-US">
<head>
<meta charset="UTF-8">
<title>I Frame</title>
</head>
<body>
<h3>clickjacking vulnerability</h3>
<iframe src="https://code4rena.com/" height="550px" width="700px"></iframe>
</body>
</html>

By Dinesh11

Notice that site is visible in the Iframe

Impact:
This is an attack that tricks a user into clicking a webpage element which is invisible or disguised as another element. This can cause users to unwittingly download malware, visit malicious web pages, provide credentials or sensitive information, transfer money, or purchase products online or Stealing NFTs.
Typically, clickjacking is performed by displaying an invisible page or HTML element, inside an iframe, on top of the page the user sees. The user believes they are clicking the visible page

**Comment by aravindb26** [comment]
Yeah it's me who found these bug, dinesh11

**Comment by CloudEllie** [comment]
Confirming this was submitted by warden dinesh11 (@aravindb26 )

**Comment by Simon-Busch** [comment]
As @aravindb26  opened an issue here : https://github.com/code-423n4/code423n4.com/issues/3861 I'll close this one to avoid duplicates :)
