### ISSUE TITLE
Warden registration should ask for wallet address

### ISSUE THREAD

**Issue by ninek9** [code-423n4/code423n4.com#41]
In addition to having a source of truth for where to send awards to, it reduces repetitive data input on findings forms.

* should potentially do a test transaction to validate?

**Comment by ninek9** [comment]
@adamavenir @dstaley in case you'd like to have input here

**Comment by heiho1** [comment]
I'm sorry...is this saying wallet addresses are going to be checked into source code and published on the website?  Why is this a good idea?

**Comment by dstaley** [comment]
Yes, that's the idea. We'd love to be able to prefill the submission form with a submitter's wallet address when they select their handle. We have no plans to display the wallet address on any surface like the leaderboard though. It would only be used on the submission form.

I also want to point out that wallet addresses are public, and [included in our findings repos](https://github.com/code-423n4/2021-04-maple-findings/blob/main/data/0xRajeev-28.json#L4).

**Comment by heiho1** [comment]
What happens if the team decides to change the wallet address?  Obviously checking wallets into a repository is as public as it can be.

**Comment by dstaley** [comment]
> What happens if the team decides to change the wallet address? Obviously checking wallets into a repository is as public as it can be.

I'm not sure I understand the question here. If a team or researcher decides to change their wallet address, all subsequent awards will go to the new address. Currently, each finding is associated with an address at creation time. We could continue this, but pull the current wallet address from this repo when the finding is submitted, or we could always use this repo as a source of truth when sending awards (so, if you update the address after submission but before rewarding, it uses the new address).

**Comment by tealtigrrr** [comment]
Closing as this is being addressed by issue #1431
