### ISSUE TITLE
[FEATURE]: Allow users to link/unlink auth addresses to their C4 accounts

### ISSUE THREAD

**Issue by captainmangoC4** [code-423n4/code423n4.com#4223]
## Problem / opportunity:
Linking multiple auth addresses to a C4 account is currently only possible through one route - changing accounts in the MetaMask extension while already logged in to our site with a MetaMask wallet.

## Desired outcome
Users can link and unlink wallet addresses with their account whether they registered with MetaMask, WalletConnect, or username/password

## Solution
The solution needs to be explored. The moralis documentation is not clear about how to do this.

**Comment by naing8392** [comment]
As always, please read my reply carefully and show mutual respect by filling in the necessary information.

**Comment by SamusElderg** [comment]
Closing this as completed
