### ISSUE TITLE
Use something other than sponsor name in report items on /reports

### ISSUE THREAD

**Issue by ninek9** [code-423n4/code423n4.com#425]
With repeat sponsors and sponsors getting different projects audited, just the sponsor name is no longer sufficient.

**Comment by DianaPerkinsDesign** [comment]
I'm only unassigning myself so someone else can grab it if they wish 😄

**Comment by tealtigrrr** [comment]
Closing. The core concern of this issue be addressed while doing the IA (see linked issues).
