### ISSUE TITLE
[BUG]: broken layout for numbers in contests page

### ISSUE THREAD

**Issue by Simon-Busch** [code-423n4/code423n4.com#4372]
## Describe the bug
Contest show broken layout for numbers

## To Reproduce
1. Go to https://code4rena.com/contests/
2. Select a finished contest

## Screenshots
<img width="830" alt="Capture d’écran 2022-10-12 à 15 40 56" src="https://user-images.githubusercontent.com/59468684/195358404-134681b7-4cb9-4503-89f8-5bffd14fdbff.png">

**Comment by joshuashort** [comment]
Fixed by data/escaping.
