### ISSUE TITLE
Contest page

### ISSUE THREAD

**Issue by adamavenir** [code-423n4/code423n4.com#48]
Create an 'everything you need to know about participating in this contest' template for active / upcoming contests which includes:

- start / end time
- prize pool(s)
- links to docs
- links to repo
- links to examples of past contests 
- links to tools, tips, educational material re: smart contract vulnerabilities

**Update:** This page will be built based on Diana's mockups (linked in the comments)

**Comment by tealtigrrr** [comment]
@DianaPerkinsDesign Is this the page that represented in this mockup? [https://code4rena.invisionapp.com/console/share/K53174L34W/768090286](https://code4rena.invisionapp.com/console/share/K53174L34W/768090286)

**Comment by DianaPerkinsDesign** [comment]
This is live! 🙌
