### ISSUE TITLE
award info (and artwork) missing on handful of contest pages after rebrand launch

### ISSUE THREAD

**Issue by loudoguno** [code-423n4/code423n4.com#508]
@DianaPerkinsDesign 
No awards on [slingshot (1)](https://code4rena.com/contests/2021-02-slingshot-finance-contest) or [ElasticDAO](https://code4rena.com/contests/2021-02-elasticdao-contest)

No artwork on anything before Reality Cards (round 1), except maple.
https://code4rena.com/contests/2021-04-vader-protocol-contest

**Comment by DianaPerkinsDesign** [comment]
We should add the awards! But the art doesn't exist, so we'll likely be leaving those blank. 

@loudoguno do you have the award amounts for those two contests?

**Comment by captainmangoC4** [comment]
@DianaPerkinsDesign I confirmed the award amounts with @loudoguno and @ninek9 a while back and just hadn't gotten around to adding those yet.
