### ISSUE TITLE
[FEATURE]: 

### ISSUE THREAD

**Issue by Talal23tt** [code-423n4/code423n4.com#5110]
## Problem / opportunity:
A clear and concise description of what the problem or opportunity is.Increase conversion speed

## Desired outcome
A clear and concise description of what this feature would bring to C4.Increase conversion speed This feature contributes to attracting a lot of partners, users and developers

## Solution
A clear and concise description of what you want to happen.Create a separate bridge from Ethereum

## Alternative
If applicable.It will be a strong competitor to the rest of the networks

## Additional context
Add any other context or screenshots about the feature request here.I don't have an extra driver. Thank you

**Comment by Talal23tt** [comment]
😊😊

**Comment by SamusElderg** [comment]
> 😊😊

Hi there, can you extend on your suggestion?
I see "Create a separate bridge from Ethereum" I am interested to know what you mean 👍

**Comment by Simon-Busch** [comment]
I'm closing this issue as this is not relevant to code4rena.com :-)
