### ISSUE TITLE
_ interpreted as italic

### ISSUE THREAD

**Issue by gpersoon** [code-423n4/code423n4.com#59]
In https://code423n4.com/reports/2021-04-basedloans/

1_000_000  is shown as 1000000 with some zeros in italic
![image](https://user-images.githubusercontent.com/5469459/120073674-a5419500-c099-11eb-8562-5d56ffb81c9a.png)

I guess this is a markdown feature and can probably be fixed by escaping the _:
1\_000\_000

**Comment by ninek9** [comment]
Nice one, thanks for the catch there!
