### ISSUE TITLE
Deploys of the site sometimes result in bad cache data

### ISSUE THREAD

**Issue by adamavenir** [code-423n4/code423n4.com#605]
Sometimes after an automatic deploy of the site, contest urls and images are mismatched. This is a serious problem because it can result in active contest pages not being accessible via links from the home page.

The easiest and thus far 100% effective method of resolving this issue is visiting [the site's Netlify build page](https://app.netlify.com/sites/code423n4-site/deploys?filter=main) and triggering a new deploy using the "Clear cache and deploy site" option.

<img width="294" alt="Screen Shot 2021-12-04 at 7 45 44 AM" src="https://user-images.githubusercontent.com/110551/144715694-2920a5d8-df4b-4c7f-a68f-f20c89d354f7.png">

If it was possible to just force a cache clear on every netlify deploy (it doesn't seem to be?), that would absolutely resolve it -- but that's not ideal anyway as it eliminates the value of cacheing in the first place.

Based on my limited understanding, there seem to be multiple potential culprits:

- Netlify site — It may work to just completely delete the current setup and re-initialize a new netlify site config. this needs a bit of coordination though as it will take the site offline for a bit in order to remove the domain config associated with the old site config and set it up for the new one
- Gatsby cache — we might try updating to a newer version of gatsby or digging deeper into any known gatsby cache issues
- serviceworker config — browsers cache service workers for 24h and don’t update on reload. A serviceworker could be interfering somehow
- npm vs yarn — we are using yarn but netlify uses npm by default. I have seen some people talk about inconsistent results from netlify builds based on yarn. haven't reviewed whether netlify is actually running yarn -- it's supposed to if it detects a yarn.lock file.
- Netlify cache bug — maybe there's a bug here somewhere? (seems least likely)

Some references:

- [Netlify's options for custom cache headers](https://docs.netlify.com/routing/headers/)
- [HTTP cache control documentation](https://docs.w3cub.com/http/headers/cache-control)
- Harry's piece on [Cache Control for Civilians](https://csswizardry.com/2019/03/cache-control-for-civilians/) is a pretty thorough reference and explainer of these configuration options.

**Comment by adamavenir** [comment]
Some notes on this issue from comments in chat:

@DianaPerkinsDesign:

> changing the actual data affects it a lot

@itsmetechjay:

> it seems like most of the cache issues happen when one contest ends and another starts. but that might not be the full story.  it could just be when it's noticed.

@dstaley:

> If anyone with devtools experience runs into this, please check the network tab and see if the incorrect image is being served from a local cache, and see if loading with cache disabled resolves the issue. Another thing to check would be if the actual generated HTML refers to the incorrect resource (which would hint that it's a Gatsby issue).

**Comment by CloudEllie** [comment]
Just wanted to add here that this issue is a pain point for contest launch management, because the current workaround requires someone to run a deploy and clear cache manually at the time every contest opens. 

I've surfaced this for @tealtigrrr but I want to make sure everyone is aware that until this issue is resolved, it's slowing down our contest processes somewhat.
