### ISSUE TITLE
Invalid pages redirect to `/index.html`, let them be 404s

### ISSUE THREAD

**Issue by DianaPerkinsDesign** [code-423n4/code423n4.com#631]
We don't have one set up yet! We'll need:

- Design / Writing (Something funny, maybe?)
- Development

**Comment by DianaPerkinsDesign** [comment]
A placeholder will also suffice for now.

**Comment by joshuashort** [comment]
The `netlify.toml` sets up a redirect for unmatched pages to the index. Removing this redirect and creating a Gatsby 404 destination should do the trick.

**Comment by Simon-Busch** [comment]
WIP, waiting for Etherean placeholder

**Comment by tealtigrrr** [comment]
![c4-404-meme](https://user-images.githubusercontent.com/92493154/166877531-c0a5ad2b-89b7-4424-a047-343351bd640e.png)

@Simon-Busch here is the artwork!

In addition to the artwork, I think we want to include the main nav/header and the footer with our social and token links. I didn't get any additional text from Etherean, so I think we can run with just the meme in the page body.

I've never used an auto redirect for A 404! I could see some value in it though, let's try it!
