### ISSUE TITLE
Add "View Repo" button to contest tile

### ISSUE THREAD

**Issue by DianaPerkinsDesign** [code-423n4/code423n4.com#636]
From Warden `Kenzo`: 
> This is quite small, but I would love if on the main page we would have after the "View Contest" button a "View Repo" button.
> Anyway as a warden I always have to go to the repo itself, so having to enter contest page first just adds an unnecessary step

**Comment by DianaPerkinsDesign** [comment]
This one's done, just stuck in a PR I need to update: https://github.com/code-423n4/code423n4.com/pull/634

**Comment by captainmangoC4** [comment]
#634 added a link to the corresponding report when available, but we still want to add a link to the repo as well.

**Comment by joshuashort** [comment]
Work might be here? https://github.com/code-423n4/code423n4.com/tree/dp/repo-links-on-contest-tiles
