### ISSUE TITLE
[BUG]: Registration stuck pending for some users

### ISSUE THREAD

**Issue by captainmangoC4** [code-423n4/code423n4.com#7054]
## Describe the bug
After some users complete registration, their accounts are stuck in a pending registration state.
I can't reproduce the issue myself - it seems to happen randomly, but very frequently. We encounter it about once a day.

## Expected behavior
When a user registers and the PR for their registration is merged, they should be able to log in successfully as soon as the site finishes redeploying.

**Comment by SamusElderg** [comment]
Closing this as no longer relevant
