### ISSUE TITLE
Automate leaderboard updates

### ISSUE THREAD

**Issue by ninek9** [code-423n4/code423n4.com#76]
Currently, the leaderboard is updated by manually updating the _data/findings/findings.json file by copy/pasting in the contents of the [sponsor]-results.json output from running the `award.ts` script in the `awardCalc` repo. There are then some manual data validation steps:

1. Verify it's still valid json.
2. Verify contest IDs are integers not strings.
3. Validate warden handles against the registered handles found in _data/handles.

Ideally, the contents of [sponsor]-results.json from the `awardCalc` repo is automatically appended to the findings.json file in this repo and has the data validation done automatically. When successful it should automatically build and deploy. This should probably be done separately from running the `award.ts` and `report.ts` scripts so that there aren't superfluous site deploys.

**Comment by CloudEllie** [comment]
Closing this as the dependencies have changed, so we're continuing discussion in the Buttons repo instead.
