### ISSUE TITLE
Confirm that the award math in our docs is correct

### ISSUE THREAD

**Issue by CloudEllie** [code-423n4/code423n4.com#765]
During my presentation about the contest process, a question was posed about the award calculation summary [here](https://docs.code4rena.com/#incentive-model-and-awards), and I confess I'd never thought to question it. 

I tried running some sample numbers through it, and the results seemed way off to me, so I suspect there is something off, though I'm not able to diagnose what it might be.

Can someone with access to the awardcalc script review the actual calculations against the math notation and confirm and/or amend it so that it's accurate?

**Comment by joshuashort** [comment]
If https://github.com/code-423n4/buttons/blob/7baf46bc42b24216bd172a54ca0696ffb1bf0fb0/src/award/utils.ts#L28-L29 is what's used for the awardcalc, that's

``` 
const pie = multiplier * Math.pow(0.9, split - 1);
const slice = pie / split;
```

The documentation differs by shrinking the pool with a single finding; it should be subtracting 1 from the findingCount in the exponent:

```
Low Risk Shares:   1 * (0.9 ^ (findingCount - 1)) / findingCount
Med Risk Shares:   3 * (0.9 ^ (findingCount - 1)) / findingCount
High Risk Shares: 10 * (0.9 ^ (findingCount - 1)) / findingCount
```

**Comment by joshuashort** [comment]
Docs updated https://github.com/code-423n4/docs/pull/4
