### ISSUE TITLE
Confusing sort order of new contests

### ISSUE THREAD

**Issue by gpersoon** [code-423n4/code423n4.com#77]
Steps:
- goto https://code423n4.com  (observe the sort order of the contests)
- click on Leaderbord
- click on the "back" button
- now the contests are sorted in reverse order
See screenshot:
![image](https://user-images.githubusercontent.com/5469459/122170986-7d1aaa00-ce7f-11eb-818f-d630ee5653c3.png)

**Comment by ninek9** [comment]
Ha! That's a fun one! Nice find, thanks @gpersoon.

**Comment by DianaPerkinsDesign** [comment]
Fixed by #156
