### ISSUE TITLE
Give the current contest a (slightly) different visual

### ISSUE THREAD

**Issue by gpersoon** [code-423n4/code423n4.com#78]
When looking at a glance at the current contest, its difficult to see the difference between the current contest and the next contest.

Last time there was no contest, I looked at the page and thought I had overlooked the active contest.
See snippets below:
![image](https://user-images.githubusercontent.com/5469459/122171977-9a03ad00-ce80-11eb-9728-9e30756ed1a2.png)

This could easily be fixed by giving the current contest a (slightly) different visual

**Comment by DianaPerkinsDesign** [comment]
I believe we've solved this with the redesign, but please let me know if I'm mistaken and it's still looking confusing!
