### ISSUE TITLE
Set character limit on warden registration form

### ISSUE THREAD

**Issue by DianaPerkinsDesign** [code-423n4/code423n4.com#796]
Set a character limit for `handle` on the warden registration form. I don't currently have a suggestion for what the limit should be, but I would say to view all handles and see what the natural maximum seems to be. Perhaps `10`?

While we're in here, let's change the label from `handle` to `username`.

**Comment by captainmangoC4** [comment]
The longest one currently is 20 characters - "toastedsteaksandwich" - so I'm thinking we can go with 25.
