### ISSUE TITLE
Leaderboard data discrepancy for gas optimization counts 

### ISSUE THREAD

**Issue by CloudEllie** [code-423n4/code423n4.com#881]
Warden `Pedroais` pointed out a discrepancy on the Leaderboard -- see this post: https://discord.com/channels/810916927919620096/859583659678105630/933787892864663582

I've checked and the findings.csv lists 4 gas opts for that warden, but the leaderboard says 0. 

It looks to me like some of them are correct (e.g. warden `nedodn`) but others are off, e.g. `jah`.

I have not investigated to see if the counts are off for other data displayed (winnings, all findings, high, med).

**Comment by DylanPokun** [comment]
Hello to the team! Well, I'm the same as Pedroais. It says 13 submissions, and only 1 contest was judged for me (Yeti). I did submit exactly 13 findings on it but 12 of them were Gas related 🤣 (and 1 was either low or NC)
So, it's impossible for there to be 0 in gas
![C4Capture](https://user-images.githubusercontent.com/47150934/150594943-e8f118d1-c5cd-4152-9d3d-24f616973256.PNG)
